version: '3'
services:
    react-app:
        build: 
            context: .
            dockerfile: Dockerfile
        volumes:
            - ./:/app
        expose:
            - "3000"
        ports:
            - "3000:3000"
        command: ["yarn", "start"]